---
name: Tag rajbos on new issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  tag-rajbos:
    # Only run on the main repository, not on forks
    if: github.repository == 'xebia/github-copilot-premium-reqs-usage'
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Tag rajbos on new issue
        if: github.event_name == 'issues'
        uses: devops-actions/issue-comment-tag@v0.1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          team: rajbos
          issue: ${{ github.event.issue.number }}

      - name: Tag rajbos on new PR
        if: github.event_name == 'pull_request'
        uses: devops-actions/issue-comment-tag@v0.1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          team: rajbos
          pr: ${{ github.event.pull_request.number }}
